export { default as ScrollDownAnimate } from './ScrollDownAnimate'
export { default as ImageJumbotron } from './ImageJumbotron'
export { default as Heading1 } from './Heading1'
export { default as Heading2 } from './Heading2'
export { default as DescHeading } from './DescHeading'
